// React/src/App.js
import { useCallback } from 'react';

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css';

import TagBox from 'devextreme-react/tag-box';
import DataSource from 'devextreme/data/data_source';

import { products } from './data';

const dataSource = new DataSource({
  store: {
    data: products,
    type: 'array',
    key: 'ID'
  },
  group: 'Category'
});

const dropDownOptions = {
  height: 300
};

function App() { 
  const onValueChanged = useCallback((e) => {
    console.log(e.previousValue);
    console.log(e.value);
  }, []);

  return (
    <TagBox
      id="tagBox"
      dataSource={dataSource}
      valueExpr="ID"
      displayExpr="Name"
      searchEnabled={true}
      showSelectionControls={true}
      grouped={true}
      multiline={true}
      maxDisplayedTags={6}
      onValueChanged={onValueChanged}
      dropDownOptions={dropDownOptions}
    />
  );
}

export default App;

// Vue/src/App.vue
<template>
  <DxTagBox
    id="tagBox"
    :data-source="dataSource"
    value-expr="ID"
    display-expr="Name"
    :search-enabled="true"
    :show-selection-controls="true"
    :grouped="true"
    :multiline="true"
    :max-displayed-tags="6"
    @value-changed="onValueChanged"
    :drop-down-options="dropDownOptions"
  />
</template>

<script>
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import { DxTagBox } from 'devextreme-vue';
import DataSource from 'devextreme/data/data_source';
import { products } from './data';

export default {
  name: 'App',
  components: {
    DxTagBox
  },
  data() {
    return {
      dataSource: new DataSource({
        store: {
          data: products,
          type: 'array',
          key: 'ID'
        },
        group: 'Category'
      }),
      dropDownOptions: {
        height: 300
      }
    };
  },
  methods: {
    onValueChanged(e) {
      console.log(e.previousValue);
      console.log(e.value);
    }
  }
};
</script>

<style>
#tagBox {
  width: 500px;
}
</style>
