// React/src/App.js
import { useCallback } from 'react';

import 'devextreme/dist/css/dx.light.css';
import './App.css';

import TagBox from 'devextreme-react/tag-box';
import DataSource from 'devextreme/data/data_source';

import { data } from './data';

const dataSource = new DataSource({
  store: {
    data: data,
    type: 'array',
    key: 'ID'
  },
  group: 'Category'
});

const dropDownOptions = {
  height: 300
};

function App() { 
  const onValueChanged = useCallback((e) => {
    console.log(e.previousValue);
    console.log(e.value);
  }, []);

  return (
    <TagBox
      id="tagBox"
      dataSource={dataSource}
      valueExpr="ID"
      displayExpr="Name"
      searchEnabled={true}
      showSelectionControls={true}
      grouped={true}
      multiline={true}
      maxDisplayedTags={6}
      label="Products"
      labelMode="floating"
      onValueChanged={onValueChanged}
      dropDownOptions={dropDownOptions}
    />
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import { AppService, Item } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
    dataSource: DataSource;
    data: Item[];
    dropDownOptions: any;

    constructor(service: AppService) {
        this.data = service.getItems();
        this.dataSource = new DataSource({
            store: {
                data: this.data, 
                type: 'array',
                key: "ID", 
            },
            group: "Category"
        });

        this.dropDownOptions = {
            height: 300
        };
    }

    onValueChanged(e) {
        console.log(e.previousValue);
        console.log(e.value);
    }
}

<dx-tag-box
    id="tagBox"
    [dataSource]="dataSource"
    valueExpr="ID"
    displayExpr="Name"
    [searchEnabled]="true"
    [showSelectionControls]="true"
    [grouped]="true"
    [multiline]="true"
    [maxDisplayedTags]="6"
    label="Products"
    labelMode="floating"
    (onValueChanged)="onValueChanged($event)"
    [dropDownOptions]="dropDownOptions">
</dx-tag-box>
